name: CMake MSYS2

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 7 1 * *'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sys: [mingw64, mingw32, ucrt64, clang64]
        BUILD_TOOL: [Ninja, "MSYS Makefiles", "MinGW Makefiles"]
    name: ${{matrix.sys}} ${{matrix.BUILD_TOOL}}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            base-devel
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
      - name: Configure & Build
        run: |
          cmake -G "${{matrix.BUILD_TOOL}}" -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build build --config ${{env.BUILD_TYPE}}
      - name: Test
        run: |
          ctest -C ${{env.BUILD_TYPE}}
      
