name: CMake Native

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 7 1 * *'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - name: Test
        run: ctest -C ${{env.BUILD_TYPE}}
      
