name: Functional Example

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * 5'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    name: mingw64 Build with Initial Boot
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            base-devel
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
      - name: Configure & Build
        run: .\\bootstrap.bat
      - name: Initial Boot Example
        run: powershell -ExecutionPolicy ByPass -File .\\scripts\\exampleExpectLua.ps1 -STEAM_LOGIN_COOKIE=${{secrets.STEAM_LOGIN_COOKIE}}
      
