name: Functional Example

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * 5'

jobs:
  MinGW64:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    name: MSYS2 MinGW-w64 Build with Initial Boot
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            base-devel
            make
            expect
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
      - name: Configure & Build
        run: |
          cmake -G Ninja -S . -B build -DENABLE_DEBUG=ON
          cmake --build build
      - name: Initial Boot Example
        run: scripts/exampleExpect.tcl ${{secrets.STEAM_LOGIN_COOKIE}}
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Linux Build with Initial Boot
    steps:
      - uses: actions/checkout@v3
      - name: Install Deps
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev expect
      - name: Configure & Build
        run: |
          cmake -S . -B build -DENABLE_DEBUG=ON
          cmake --build build
      - name: Initial Boot Example
        run: |
          chmod u+r+x scripts/exampleExpect.tcl
          scripts/exampleExpect.tcl ${{secrets.STEAM_LOGIN_COOKIE}}
  MacOS:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    name: MacOS Build with Initial Boot
    steps:
      - uses: actions/checkout@v3
      - name: Configure & Build
        run: |
          cmake -S . -B build -DENABLE_DEBUG=ON
          cmake --build build
      - name: Initial Boot Example
        run: |
          chmod 500 scripts/exampleExpect.tcl
          scripts/exampleExpect.tcl ${{secrets.STEAM_LOGIN_COOKIE}}
